package homework060826;

public enum ATM_State {
    IDLE,
    CARD_INSERTED,
    PIN_VERIFICATION,
    AUTHENTICATED,
    TRANSACTION_IN_PROGRESS,
    BLOCKED,
    CARD_EJECTED,
    INVALID_TRANSACTION,
}
